language: ruby
addons:
before_script:
  - gem install markdown_slider

script: 
  - mkdir release
  - md-slider _sandbox/test_markdown_slider.md > release/index.html
  
after_script:
  - ./.travis.sh deploy

env:
  global:
    - GH_BUILD_REPORT=ikeyat/ikeyat.github.io
    - secure: "KSxgEDfpnRqIuD9MQ+LACS8ZhLB9roordtcUWUKTnzmyHy0iKpAWFk+fmEgcvgtVyxd6N0VG0kh6aFvgMS7e+GMGCJA8L5w1Ln7XV52py9TvhiGp7zhOGUiTEi2KId16VMlsK/oVOPT//8kDPV7oSzAiIe/vSvGULaGd6LpPqFPruN+MaBgkbC3MCsOW3Wk1yqzW6cjq9rlpFaIjuM4v8/rM1XhXfLKoFCwtq5oqdnCQtCL5BFSLNP+41yWy6W9KIZ+StqS1C0TqbE1XPi1WyEdfdb2dz3Fm1aiWOswBOgKxArfBO52zdUX1UsMpFRw3QBZyaJaz2JFAfNj9JFYhjaSMD/gZoqzrMbF9kuI0Ml5kwuIAhYkkvlS8BQBtKP9jSXJibsVYVWnBIFY2vLcwg2AvCYmWbCb0cX2l5Yxzt2X+qavIRKpGP2A9lCNnobn2JBrqiebf0zwzHaZlYOioIlKlMgwOyL21PJnuLvpXoqBDcO7rGVj542BehZy3jalRUXsUxrpYIOshpg4m/7AcxQnClXtcdLfq/sJHYmZkmUAJjJaS+vozuU3dUCTxrd+3ceH7T94Cekdwq49ZplRGUeIbvlBbJdfZMQFudI4evzcrluzoJH1ISjYhrBQR3L4sdcxurZIA5tgxrqknkC91TzbeOKIef+nJQ6BES6bo08I="
    - secure: "oT8OOvqNpzPLu9mJjsYv+N6Tt7nFrkKRQQA3lQ3fLlO2WLyf1EPOVI/D8Z+lNSEJ1ZOfLAClqpWTaLvGasShZCogNTvw68p8eMEto9KKu7MiG969/WwwHOOqb4rTKVTKUE5mX5N0j1l5YEV6RPUzpzdmfzQ0HUk8K7QYkt7qelQ4g1Dx6o2tofzwhMyMQ41bwVHttkOfv+JzbZ86eBci/A2kZnPgi9ZyEvLL+dZpKHIXFd2OEMhMNzxe+6c9DcWBIa12wIR9eFe3ySt5tT8xIu8slp6bV0VrBal+nWPvG4yNbC6O0Z4jKGQl3+oVR2KUdPnYPlDDVxnBeY8rfH+a2W8Q/7Lv3vYukLjt4VkTFZeI0mqAU9QVo4amhTwaygS0uGuqgoAo3neczVT2FnkIlpBHm2qSEk2lYS5sJPGbX9K3hrVo83s0L6CVnBeJ7+1u6j3vP4Pod73SfgCGlEQ9EfqxOouLq+UqxjDJJ0zGy9uBI2/uqoYbZ+y5o0XXnJVN648kkWJ3Ksw3vQX2xZKf3Gs7ZrNASG5ElXY5aPLoUwoJdM2glu6z0wgShGPzmllvdUjx045ixZe5culsGj1qQivHRK37A0qbsgCMZYFYCq26PoM1GnRESze3OIyssjVDFUCh84WtyJyNa+0br7Wb8GaLLlaWMjB/PuSR49eauo8="
