language: ruby
addons:
before_script:
  - gem install markdown_slider
  - mkdir $BUILD_DIR
script: |
    LINKS_TEXT=""
    find $TRAVIS_BUILD_DIR -maxdepth 1 -type d | while read DIR
    do
      TARGET_DIR=`basename $DIR`
      if [ $TARGET_DIR != `basename $TRAVIS_BUILD_DIR` ] && [ $TARGET_DIR != `basename $BUILD_DIR` ]
      then
        mkdir $BUILD_DIR/$TARGET_DIR
        md-slider $TRAVIS_BUILD_DIR/$TARGET_DIR/*.md > $BUILD_DIR/$TARGET_DIR/index.html
        LINKS_TEXT="$LINKS_TEXT<li><a href=\"http://ikeyat.github.io/slides/$TARGET_DIR\">$TARGET_DIR</a></li>\n"
      fi
    done
    cat $TRAVIS_BUILD_DIR/$INDEX_FILE | sed "s/#links#/$LINKS_TEXT/g" > $BUILD_DIR/$INDEX_FILE
after_success:
   - set +x
   - echo "machine github.com" >> ~/.netrc
   - echo "login $GH_LOGIN"    >> ~/.netrc
   - echo "password $GH_TOKEN" >> ~/.netrc
   - set -x
   - git config --global user.email 'travis@travis-ci.org'
   - git config --global user.name 'travis'
   - rm -Rf $WORK_DIR
   - git clone --quiet "https://github.com/$GH_DEPLOY_REPO.git" $WORK_DIR
   - cd $WORK_DIR
   - git checkout -b $BRANCH_NAME
   - cd $GH_DEPLOY_PATH
   - git rm -r $GH_DEPLOY_PATH/*
   - mkdir $GH_DEPLOY_PATH
   - cp -R $BUILD_DIR/* $GH_DEPLOY_PATH/
   - cd $GH_DEPLOY_PATH
   - cp $BUILD_DIR/$INDEX_FILE $GH_DEPLOY_PATH/$INDEX_FILE
   - git add -A
   - git commit -q -m "Automatically updated by Travis build $TRAVIS_BUILD_NUMBER"
   - git push origin $BRANCH_NAME --force
   - rm -v ~/.netrc

env:
  global:
    - INDEX_FILE=index.html
    - BUILD_DIR=$TRAVIS_BUILD_DIR/build
    - WORK_DIR=$TRAVIS_BUILD_DIR/work
    - GH_DEPLOY_REPO=ikeyat/ikeyat.github.io
    - GH_DEPLOY_PATH=$WORK_DIR/slides
    - BRANCH_NAME=travis-latest-snapshot
    - secure: "KSxgEDfpnRqIuD9MQ+LACS8ZhLB9roordtcUWUKTnzmyHy0iKpAWFk+fmEgcvgtVyxd6N0VG0kh6aFvgMS7e+GMGCJA8L5w1Ln7XV52py9TvhiGp7zhOGUiTEi2KId16VMlsK/oVOPT//8kDPV7oSzAiIe/vSvGULaGd6LpPqFPruN+MaBgkbC3MCsOW3Wk1yqzW6cjq9rlpFaIjuM4v8/rM1XhXfLKoFCwtq5oqdnCQtCL5BFSLNP+41yWy6W9KIZ+StqS1C0TqbE1XPi1WyEdfdb2dz3Fm1aiWOswBOgKxArfBO52zdUX1UsMpFRw3QBZyaJaz2JFAfNj9JFYhjaSMD/gZoqzrMbF9kuI0Ml5kwuIAhYkkvlS8BQBtKP9jSXJibsVYVWnBIFY2vLcwg2AvCYmWbCb0cX2l5Yxzt2X+qavIRKpGP2A9lCNnobn2JBrqiebf0zwzHaZlYOioIlKlMgwOyL21PJnuLvpXoqBDcO7rGVj542BehZy3jalRUXsUxrpYIOshpg4m/7AcxQnClXtcdLfq/sJHYmZkmUAJjJaS+vozuU3dUCTxrd+3ceH7T94Cekdwq49ZplRGUeIbvlBbJdfZMQFudI4evzcrluzoJH1ISjYhrBQR3L4sdcxurZIA5tgxrqknkC91TzbeOKIef+nJQ6BES6bo08I="
    - secure: "KXYrD8MdDpTjrNRrfrBj2pKsfGOX5YAP92g5UYkzPF+nfEH2H5FzXcjW1LyfQFYSfTQ1B0HrWmYuGdA06Q0dn5aTHzD3juGYEACcDbNl9YogzjHruLIsXfxJD5qjNLI1JImG8hQNYhwWKygPDxD7gtS4rYXs0nNLdezeI3y7NHWV1cOEaB0Zzc2jaRbmFF05/yvr/9GiFvgAa6LpT+e06Ia/RIAej+SbCwzzNkkEdrNHp0tnCLKYhD2nXVCdmk3oQ0mAaKGd2XlzXk5gtT3uhuPgIuFq71bzeK7AG6kLtEh9IZe2igdOSSunZu7rXfoZWimDvgFZPcoYSs0W+e2VRRXXDUDx/MKY8CjPWUoImXzpLaiME5Hszu+N6baUyjCw7S6FGHRoo1eNqKk4Sr2ubeJJVJz012b4HD69aML9t8r16bb74UYdAPv7djbbJKGbOIWJr/fQYCgtXlf8vnLnKoUrUJo0cZBxNf0034gVeuAJpF1604sxl0nNkn7tuTHQULFWnZ7SHTCGjsUXxgzbzCRFbcTtaqOF9E+M/Ik/uNQXdncfH460977GAH+n9JsSYW7lw+k/9H6oahLWXOYKmzpWCXaf4QZdqLuWOONkTrtmTfHLzUEb/JcGYSERY+yaipajVhkrSad3P6nzZH64nc0M9U5trA8X8tEfvQFdk/U="
    
