language: ruby
addons:
before_script:
  - gem install markdown_slider
  - mkdir $BUILD_DIR
script: |
    export LINKS_TEXT=""
    find $TRAVIS_BUILD_DIR -maxdepth 1 -type d | while read DIR
    do
      TARGET_DIR=`basename $DIR`
      if [ $TARGET_DIR != `basename $TRAVIS_BUILD_DIR` ] && [ $TARGET_DIR != `basename $BUILD_DIR` ]
      then
        mkdir $BUILD_DIR/$TARGET_DIR
        md-slider $TRAVIS_BUILD_DIR/$TARGET_DIR/*.md > $BUILD_DIR/$TARGET_DIR/index.html
        cp -r $TRAVIS_BUILD_DIR/$TARGET_DIR/* $BUILD_DIR/$TARGET_DIR/
        export LINKS_TEXT="${LINKS_TEXT}<li><a href=\"http://ikeyat.github.io/slides/$TARGET_DIR\">$TARGET_DIR</a></li>"
      fi
    done
    cat $TRAVIS_BUILD_DIR/$INDEX_FILE | sed -e "s|#links#|${LINKS_TEXT}|g" > $BUILD_DIR/$INDEX_FILE
after_success:
   - set +x
   - echo "machine github.com" >> ~/.netrc
   - echo "login $GH_LOGIN"    >> ~/.netrc
   - echo "password $GH_TOKEN" >> ~/.netrc
   - set -x
   - git config --global user.email 'travis@travis-ci.org'
   - git config --global user.name 'travis'
   - rm -Rf $WORK_DIR
   - git clone --quiet "https://github.com/$GH_DEPLOY_REPO.git" $WORK_DIR
   - cd $WORK_DIR
   - git checkout -b $BRANCH_NAME
   - cd $GH_DEPLOY_PATH
   - git rm -r $GH_DEPLOY_PATH/*
   - mkdir $GH_DEPLOY_PATH
   - cp -R $BUILD_DIR/* $GH_DEPLOY_PATH/
   - cd $GH_DEPLOY_PATH
   - cp $BUILD_DIR/$INDEX_FILE $GH_DEPLOY_PATH/$INDEX_FILE
   - git add -A
   - git commit -q -m "Automatically updated by Travis build $TRAVIS_BUILD_NUMBER"
   - git push -quiet https://$GH_TOKEN@github.com/$GH_DEPLOY_REPO.git $BRANCH_NAME --force
   - rm -v ~/.netrc

env:
  global:
    - INDEX_FILE=index.html
    - BUILD_DIR=$TRAVIS_BUILD_DIR/build
    - WORK_DIR=$TRAVIS_BUILD_DIR/work
    - GH_DEPLOY_REPO=ikeyat/slides-publish
    - GH_DEPLOY_PATH=$WORK_DIR/slides
    - BRANCH_NAME=gh-pages
    - secure: "a4lSXHWLtevPFNYPN2Q89gpCUFu2szY/5DS69TgXiHAwI/Yd9Byah7DIuPL0L4uPAQuoJheqRpoJUjI1WO6GM0mYJUcwGJQZZFlCc+7D8I3VpkLagCQ7L/aWKnuWgoE/5y4VpOukP8YE4m46txpnMnNx38Qe3bp5KVv9cVywmm0cYf4R/66xkaw5/0ZSp8iPpMByrzhY9w2VAKfru09p+eziocVYGMBBU3ZMEllVmNwFaAFNZUmDGuNuqWEFbduUg/fM92y3tr8SKne0ZWVDDwMrBJDrt3osXQD6HOArLJ5aedmV4NRtsEYKfjOnFFsapaWbuz0ZoAT1Hvv0YOZvzFj3qyJurB4XjxkNTfp4sWxzekwIIjvt2UBrazMS4rrd1h9wxg35aL0yq4dCPbJGNk30bpf0AkiAHG7VWIhEZLSNIThN+W6n8SP+DTecjJaUspBV86rXAkK7lA7UCjmm8/05dsgu1p4Drutpnnh/6wlW7oDFi0AplLgMPjofLZDZDLl/4W4PgULnU2ZKyuW4O0rwnm3TcWXX9mRQFwTTfTWwQvCgWgQdzWqltRtBnUEm/sorh2xDuGljtu/AA5MFDPNgEEwEP5zCUXBeHQfU5+He3F5mpfRf1I6B1uoftAZRRLeFFP0e/GVbt7f2JRSuQzkmYaAB6DWGeP336OfiRC0="
    - secure: "FuFWTGpKcqfJgrIV/XA+AMrkzaKJ3FmfGXkUW6/GWvVhN2MZ6sKJOG61rtHaToHvrvtaR1UdNh/Fp7lL6TMtG/tar3RMdcnnKHIsiNEqMT6Fh9BQHmqu+8uOrBKvPNjzsOFsn20uVi+LanQCFCg+SDPhSoBfvn46qp/RkhglRYekTPP+eB4WBqRIixBJvLfQgt+z7aSvdsdjMcUrgDK3rXqPYZMOMAH0mcYiJVkfLY5FcEjg77+9AnmyUb/oK2HMXM9ujdztyPvMOGgDAPp4iglxi6XQfHQhPnlQtuNC6k1maWZGV4wHwD3FcKJPOWiU5gDAn3bUVrA2GZyxfL8J5rvBN5gDXB+kxNl0Oe055x/z73G7tGSCh31a51v586RWhGEDSt+cDDJww/8oYLjiaexHz38thAYNLhtl3yBB9u2qr+8nP2P7yoA7pMYNxWEuur5rAfESqvW6y6cTuXRJRoAIR6afs6Bp75V1KXChs82OA0l4KQIqBmElzLjc7Ip0iwCaqfd8bJq9nWcfmQZGOM39fx7OqqUBF0gFrdbvRT8jsMzmNorj1nCxz7np8KKGSXkBeagCNw8IzxpNtXYidaDDYDXaw2eoWWyRM0OPOLCKJhCllRlhSebjZe9oJ4BNHybepFjy+fBnnSKHvH3DnXbnTxNX+hVonHEK71lAejw="
    
